### ISSUE TITLE
Resnet3D

### ISSUE THREAD

**Issue by nationalflag** [MIPT-Oulu/pytorch_bn_fusion#1]
In my experiment in Resnet3D(50), the "convert_resnet_family" will speed up the inference, but "fuse_bn_recursively" not.

**Comment by lext** [comment]
@nationalflag if this is a 3D network, we do not support it just yet. It only works with 2D conv. Please, also pay attention that Conv+BN must be within one Sequential block.

**Comment by nationalflag** [comment]
I just wonder why only modify the Conv+BN to within one Sequential block will speed up my network.

**Comment by lext** [comment]
@nationalflag Please, address this question to PyTorch developers. In theory, it should not. In my experiments, ResNets from `torchvision` get up to 30% boost.

**Comment by lext** [comment]
This issue will be closed due to a non-relevant question
